language: node_js

node_js: '6'

sudo: required

services:
  - docker

before_install:
  - docker-compose up -d

deploy:
- provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  local_dir: dpl_cd_upload
  skip_cleanup: true
  on: &2
    repo: benwfreed/eatlanta-server
    branch: develop
  bucket: eatlanta-server
  region: us-east-1
- provider: codedeploy
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: eatlanta-server
  key: latest.zip
  bundle_type: zip
  application: eatlanta-server
  deployment_group: eatlanta-server
  region: us-east-1
  on: *2
    branch: develop
script:
  - zip -r latest *
  - mkdir -p dpl_cd_upload
  - mv latest.zip dpl_cd_upload/latest.zip
